path: /home/arch3nemy7/Documents/bacterial-gan-augmentation/data/01_raw/1. DeepDataSet/SegmentationDataSet
train: splits_absolute/train.txt
val: splits_absolute/val.txt
test: splits_absolute/test.txt

# Images are in 'images', Labels are in 'labels' parallel to it.
# YOLO auto-resolves this structure: ../images/file.jpg -> ../labels/file.txt

nc: 2
names:
  0: gram_negative
  1: gram_positive
